DROP TABLE BOOKS;

CREATE TABLE BOOKS (id INTEGER PRIMARY KEY, name VARCHAR2(20), rating INTEGER);

INSERT INTO BOOKS VALUES (1, 'english', 5);
INSERT INTO BOOKS VALUES (2, 'chinese', 3);
INSERT INTO BOOKS VALUES (3, 'japanese', 1);
SELECT * FROM BOOKS;

DROP TABLE BOOKS;
